version: '3.1'

services:
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  instance1:
    image: aymanebel/booky:latest
    environment:
      - DB_USER=aymane
      - DB_PASS=aymane@123
      - DB_NAME=book_go
      - DB_HOST=postgres
    ports:
      - 8001:8000