version: '3.1'

services:
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  instance1:
    image: aymanebel/booky:latest
    #container_name: instance1
    environment:
      - DB_USER=aymane
      - DB_PASS=aymane@123
      - DB_NAME=book_go
      - DB_HOST=postgres
    networks:
      - load
  # instance2:
  #   image: aymanebel/booky:latest
  #   container_name: instance2
  #   environment:
  #     - DB_USER=aymane
  #     - DB_PASS=aymane@123
  #     - DB_NAME=book_go
  #     - DB_HOST=postgres
  #   ports:
  #     - 8002:8000
  #   networks:
  #     - load
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - load
networks:
  load: